server:
  port: 8008
  
spring:
  data:
   neo4j:
     uri : bolt://0.0.0.0
     username: neo4j
     password: 123456  

eureka:
  client:
    serviceUrl:
      defaultZone: http://13.233.180.226:8091/eureka/

logging:
  level:
    org.springframework.web: ERROR
    com.stackroute: DEBUG
    spring.data.mongodb: ERROR
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
  path: logs
file: ${logging.path}/matchmaking-platform.log
